#!/bin/sh

# Set output file
output_file="build.ninja"

# Write the header of build.ninja
cat > "$output_file" << 'EOF'
# Autogenerated Ninja build file

rule compile
  command = tcc -L./ $in -o $out -lsqlite3 -ljson-c -lcrypto -ljwtc
  description = Compiling $in to $out

EOF

# Get top-level .c files (CGI sources), excluding shell scripts or non-C files
cgi_sources=$(find . -maxdepth 1 -type f -name "*.c" ! -name "*_entrypoint.sh" | sort)

# Get .c files in ./lib excluding test_*.c
lib_sources=$(find ./lib -type f -name "*.c" ! -name "test_*.c" | sort)

# Check if lib_sources is empty
if [ -z "$lib_sources" ]; then
  echo "# No library sources found in ./lib" >> "$output_file"
  lib_sources_list=""
else
  # Convert to space-separated list
  lib_sources_list=$(printf "%s " $lib_sources)
fi

# Generate build rules for each CGI
for cgi_src in $cgi_sources; do
  # Get the base name (without path or extension)
  cgi_name=$(basename "$cgi_src" .c)
  cgi_out="${cgi_name}.cgi"

  # Build rule with proper escaping and formatting
  {
    printf "build %s: compile %s %s\n" "$cgi_out" "$cgi_src" "$lib_sources_list"
  } >> "$output_file"
done
