#!/bin/sh

output_file="build.ninja"

cat > "$output_file" << 'EOF'
# Autogenerated Ninja build file

rule compile
  command = tcc -L./ $in -o $out -lsqlite3 -ljson-c -lcrypto -ljwtc -lsanitizec -lsodium
  description = Compiling $in to $out

EOF

cgi_sources=$(find . -maxdepth 1 -type f -name "*.c" ! -name "*_entrypoint.sh" | sort)

lib_sources=$(find ./lib -type f -name "*.c" ! -name "test_*.c" | sort)

if [ -z "$lib_sources" ]; then
  echo "# No library sources found in ./lib" >> "$output_file"
  lib_sources_list=""
else
  lib_sources_list=$(printf "%s " $lib_sources)
fi

for cgi_src in $cgi_sources; do
  cgi_name=$(basename "$cgi_src" .c)
  cgi_out="${cgi_name}.cgi"

  {
    printf "build %s: compile %s %s\n" "$cgi_out" "$cgi_src" "$lib_sources_list"
  } >> "$output_file"
done
