#!/bin/bash
set -eu

# generate_graphs.sh
# - Generates .dot and .svg callgraphs using cflow + dot
# - Outputs into docs/graphs and a simple docs/index.html

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTDIR="$ROOT/docs/graphs"
mkdir -p "$OUTDIR"

# collect source files
BACKEND_C=$(find "$ROOT/backend" -maxdepth 1 -name '*.c' -print)
LIB_C=$(find "$ROOT/backend/lib" -name '*.c' -print || true)

# Temporary dot file
tmpdot() {
    echo "$OUTDIR/$(basename "$1" .c).dot"
}

# Generate per-backend graph. If file contains main(), use --main=main (clear entry).
for src in $BACKEND_C; do
    bn=$(basename "$src" .c)
    DOT=$(tmpdot "$src")

    if grep -q 'int[[:space:]]\+main[[:space:]]*(' "$src" 2>/dev/null; then
        echo "Generating callgraph for $bn (entry: main)"
        cflow --format=graphviz --main=main $LIB_C "$src" > "$DOT" 2>/dev/null || \
            cflow --format=graphviz $LIB_C "$src" > "$DOT"
    else
        echo "Generating module callgraph for $bn"
        # include lib and the single backend file to get context
        cflow --format=graphviz $LIB_C "$src" > "$DOT" 2>/dev/null || \
            cflow --format=graphviz $LIB_C "$src" > "$DOT"
    fi

    # Convert to svg
    dot -Tsvg "$DOT" -o "$OUTDIR/$bn.svg"
done

# Generate a monolithic lib graph (all library sources)
if [ -n "$LIB_C" ]; then
    DOT_LIB="$OUTDIR/lib_all.dot"
    cflow --format=graphviz $LIB_C > "$DOT_LIB" 2>/dev/null || cflow --format=graphviz $LIB_C > "$DOT_LIB"
    dot -Tsvg "$DOT_LIB" -o "$OUTDIR/lib_all.svg"
fi

# Build a minimal index.html
IDX="$ROOT/docs/index.html"
cat > "$IDX" <<'HTML'
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Call Graphs</title>
  <style>
    body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial; padding: 24px; }
    .grid { display:grid; grid-template-columns: repeat(auto-fit,minmax(320px,1fr)); gap: 18px; }
    .card { border:1px solid #e1e1e1; padding:12px; border-radius:8px; background:#fff; }
    .card h3{ margin:0 0 8px 0; font-size:15px; }
    .svgWrap{ height:420px; overflow:auto; border:1px dashed #ddd; padding:6px; background:#fafafa; }
    a.meta{ font-size:13px; color:#333; text-decoration:none; }
  </style>
</head>
<body>
  <h1>Call Graphs (auto-generated)</h1>
  <p>Generated by <code>scripts/generate_graphs.sh</code>. Rendered with Graphviz.</p>
  <div class="grid">
HTML

# Insert each svg as a card
for svg in $(ls "$OUTDIR"/*.svg 2>/dev/null || true); do
    name=$(basename "$svg")
    title=$(basename "$svg" .svg)
    cat >> "$IDX" <<HTML
    <div class="card">
      <h3>$title</h3>
      <div class="svgWrap">
        <object type="image/svg+xml" data="graphs/$name" width="100%"></object>
      </div>
      <p><a class="meta" href="graphs/$name" target="_blank">Open SVG</a></p>
    </div>
HTML
done

cat >> "$IDX" <<'HTML'
  </div>
</body>
</html>
HTML

echo "Graphs written to $OUTDIR and index at docs/index.html"
